In [1]:
import ipywidgets as widgets

In [2]:

from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
import time
import pandas as pd

In [3]:
def versionOne(job_listings, jobs_data):
    # Print the job titles
    for job_listing in job_listings:
        
        # Gathering Title name data
        try:
            title = job_listing.find_element(By.XPATH, './/div[@class="job-title mt-xsm"]')
            title = title.text
        except Exception as e:
#             print("No title was found: ")
            title = "Data Scientist"
            pass
    
        # Gathering Company name data
        try:
            company = job_listing.find_element(By.XPATH, './/div[@class="job-search-8wag7x"]')
            company = company.text
        except Exception as e:
#             print("No Company was found: ")
            company = '-'
            pass
        
        # Gathering Location name data 
        try:
            location = job_listing.find_element(By.XPATH, './/div[@class="location mt-xxsm"]')
            location = location.text
        except Exception as e:
#             print("No location was found: ")
            location = '-'
            pass
    
        # Gathering Salary name data
        try:
            salary = job_listing.find_element(By.XPATH, './/div[@class="salary-estimate"]')
            salary = salary.text
        except Exception as e:
#             print("No salary was found: ")
            salary = '-'
            pass
    
#         print(title, company, location, salary)
        jobs_data.append({'Title': title, 'Company': company, 'Location': location, 'Salary': salary})
    return jobs_data

In [4]:
def versionTwo(job_listings, jobs_data):
    # Print the job titles
    for job_listing in job_listings:
        
        # Gathering Title name data
        try:
            title = job_listing.find_element(By.XPATH, './/div[@class="job-title mt-xsm"]')
            title = title.text
        except Exception as e:
#             print("No title was found: ")
            title = "Data Scientist"
            pass
        
        # Gathering Company name data
        try:
            company = job_listing.find_element(By.XPATH, './/div[@class="css-8wag7x"]')
            company = company.text
        except Exception as e:
#             print("No Company was found: ")
            company = '-'
            pass
    
        # Gathering Location name data    
        try:
            location = job_listing.find_element(By.XPATH, './/div[@class="location mt-xxsm"]')
            location = location.text
        except Exception as e:
#             print("No location was found: ")
            location = '-'
            pass
        
        # Gathering Salary name data
        try:
            salary = job_listing.find_element(By.XPATH, './/div[@class="salary-estimate"]')
            salary = salary.text
        except Exception as e:
#             print("No Salary was  found: ")
            salary = '-'
            pass
            
            
#         print(title, company, location, salary)
        jobs_data.append({'Title': title, 'Company': company, 'Location': location, 'Salary': salary})
    return jobs_data

In [41]:
def get_data(job, job_location):
    print('Looking for {} positions in {}'.format(job, job_location))
    # Set up the WebDriver
    #Initializing the webdriver
    options = webdriver.ChromeOptions()

    #Uncomment the line below if you'd like to scrape without a new Chrome window every time.
    #options.add_argument('headless')

    #Change the path to where chromedriver is in your home folder.
    driver = webdriver.Chrome(options=options)
    driver.set_window_size(1120, 1000) # Replace 'path_to_chrome_driver' with the actual path to your Chrome WebDriver executable
    wait = WebDriverWait(driver, 10)
    # Navigate to the Glassdoor website
    driver.get("https://www.glassdoor.com/Job/jobs.htm?suggestCount=0&suggestChosen=false&clickSource=searchBtn&typedKeyword="+job+"&sc.keyword="+job+"&locT=&locId=&jobType=")

    # # Locate and click the "Jobs" link
    # jobs_link = wait.until(EC.presence_of_element_located((By.XPATH, '//b[@class="lockedHomeHeader__LockedHomeHeaderStyles__mainMenuItem"]')))
    # jobs_link.click()
    
    # Make driver wait for everything to load
    driver.implicitly_wait(25)
    
    # Locate and fill in the job search keyword
#     search_box = wait.until(EC.presence_of_element_located((By.XPATH, '//input[@data-test="search-bar-keyword-input"]')))
#     search_box.send_keys(job)  # Replace 'software engineer' with your desired job search keyword

    # Locate and fill in the job search location
    location_box = wait.until(EC.presence_of_element_located((By.XPATH, '//input[@data-test="search-bar-location-input"]')))
    location_box.clear()
    location_box.send_keys(job_location)  # Replace 'San Francisco' with your desired job search location

    # Submit the job search form
    search_button = wait.until(EC.presence_of_element_located((By.XPATH, '//button[@data-test="search-bar-submit"]')))
    search_button.click()

#     #Click on the "See All Jobs" link
#     jobs_button = wait.until(EC.presence_of_element_located((By.XPATH, '//strong[@class="mr-xxsm"]')))
#     jobs_button.click()
#     # Wait for the job search results to load
#     driver.implicitly_wait(10)

    #Fetching the amount of pages the result has
#     pages = driver.find_element(By.XPATH, './/div[@data-test="pagination-footer-text"]')
# #     pages = pages.text.split()
#     print(pages.text)

    #Extracting more than one page of job results
    pages = [2 + n for n in range(0, 10)]
    jobs_data = []
    for page in pages:
        print('-' * 50)
        print('On page {}'.format(page-1))
        
        # Checking if there is a mini window to close to close and continue data mining
        try:
            mini_window_button = wait.until(EC.element_to_be_clickable((By.XPATH, './/button[@class="e1jbctw80 ei0fd8p1 css-1n14mz9 e1q8sty40"]')))
            mini_window_button.click()
        except Exception as e:
    #         print("No mini window")
            pass

        # Extract the job listings
        job_listings = driver.find_elements(By.XPATH, '//li[contains(@class, "react-job-listing css-108gl9c eigr9kq3")]')

        if page == 2:
            jobs_data = versionOne(job_listings, jobs_data)
        else:
            jobs_data = versionTwo(job_listings, jobs_data)



        try:
            path = '//button[@data-test="pagination-link-%s"]'%page
            page_button = WebDriverWait(driver, 50).until(EC.element_to_be_clickable((By.XPATH, path)))
            page_button.click()
            print('-' * 50)
        except Exception as e:
            break
        
    #Close the WebDriver
    driver.quit()
    
    df = pd.DataFrame(jobs_data)
    return df

In [ ]:
state_names=["Alabama", "Alaska", "Arizona", "Arkansas", "California",
             "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
             "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
             "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
             "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
             "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
             "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
             "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
             "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
             "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
df = pd.DataFrame()
for state in state_names:
    state_df = get_data('data scientist', state)
    datasets = [df, state_df]
    df = pd.concat(datasets)

Looking for data scientist positions in Alabama
--------------------------------------------------
On page 1
--------------------------------------------------
--------------------------------------------------
On page 2
--------------------------------------------------
--------------------------------------------------
On page 3
Looking for data scientist positions in Alaska
--------------------------------------------------
On page 1

In [ ]:
df.shape()

In [ ]:
df.head()

In [34]:
CA_data.head(120)

,Title,Company,Location,Salary
0,Senior Data Scientist (Healthcare),Alaka`ina Foundation Family of Companies3.7 ★,United States,-
1,Data Scientist II,Net2Source4.3 ★,"Los Angeles, CA",$55.00 - $58.00 Per Hour (Employer est.)
2,Data Scientist (L6) - Ads,Netflix4.3 ★,"Los Angeles, CA",$104K - $181K (Glassdoor est.)
3,Data Scientist,Numerade3.9 ★,"Los Angeles, CA",$96K - $139K (Glassdoor est.)
4,"Data Analyst / Data Scientist, Wholesale",Frontier Communications3.1 ★,"Los Angeles, CA",$89K - $149K (Employer est.)
...,...,...,...,...
115,Senior Machine Learning Engineer,Artera4.4 ★,"Los Angeles, CA",$124K - $177K (Glassdoor est.)
116,"Machine Learning Lead, Creativity Apps",Apple4.2 ★,"Culver City, CA",-
117,Senior Big Data Engineer - ML/AI,Niagara Bottling3.9 ★,"Diamond Bar, CA",$103K - $145K (Employer est.)
118,"Senior Director, Data Science",Red Bull North America4.2 ★,"Santa Monica, CA",$133K - $192K (Glassdoor est.)
119,Clinical NLP Engineer,Deep 6 AI4.0 ★,"Pasadena, CA",$140K - $180K (Employer est.)

In [35]:
TX_data.head(120)

,Title,Company,Location,Salary
0,Senior Machine Learning Engineer,Zencon Group,"Austin, TX",$70.00 - $80.00 Per Hour (Employer est.)
1,Senior Data Scientist (Healthcare),Alaka`ina Foundation Family of Companies3.7 ★,United States,-
2,Data Scientist,Wise Equation Solutions4.9 ★,"Austin, TX",-
3,Data Scientist,Abbott Laboratories3.8 ★,"Austin, TX",$57K - $113K (Employer est.)
4,Junior Data Scientist,ANALYTOS,"Austin, TX",-
...,...,...,...,...
115,"Product Engineer - Silicon Development, Autopi...",Tesla3.7 ★,"Austin, TX",$109K - $159K (Glassdoor est.)
116,Artificial Intelligence Business Development L...,Deloitte4.0 ★,"Austin, TX",-
117,"Expert Senior Manager, Machine Learning Engineer",Bain & Company4.4 ★,"Austin, TX",$261K - $313K (Employer est.)
118,Senior Machine Learning Engineer,Recruiting From Scratch3.9 ★,"Austin, TX",$150K - $200K (Employer est.)
119,Staff Machine Learning Engineer,FullStory2.8 ★,"Austin, TX",$109K - $161K (Glassdoor est.)